// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Document {
    "title": string;
    "overview": string;
    "prerequisites": string[] | null;
    "steps": Step[] | null;
}

export interface EvidenceRef {
    "evidenceId": string;
    "displayName": string;
    "included": boolean;
}

export interface Integrity {
    "status": string;
    "issues": Issue[] | null;
}

export interface Issue {
    "code": string;
    "severity": string;
    "message": string;
    "stepId"?: string;
    "evidenceId"?: string;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Generating = "generating",
    Draft = "draft",
    Checking = "checking",
    Completed = "completed",
    Failed = "failed",
};

export interface Step {
    "stepId"?: string;
    "clientKey": string;
    "title": string;
    "description": string;
    "command"?: string;
    "notes": string[] | null;
    "evidenceRefs": EvidenceRef[] | null;
}
