// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AttachHumanEvidence($in: $models.AttachHumanEvidenceInput): $CancellablePromise<$models.MutationResult<$models.EvidenceAttached>> {
    return $Call.ByID(2224839479, $in);
}

export function GenerateProcedureDraft($in: $models.GenerateProcedureDraftInput): $CancellablePromise<$models.MutationResult<$models.ProcedureGenerationAccepted>> {
    return $Call.ByID(4023294307, $in);
}

export function GetExecution($in: $models.ExecutionViewQuery): $CancellablePromise<application$0.ExecutionView> {
    return $Call.ByID(3565193614, $in);
}

export function RespondToPermissionRequest($in: $models.PermissionResponseInput): $CancellablePromise<$models.MutationResult<$models.PermissionResponseResult>> {
    return $Call.ByID(3397895456, $in);
}

export function RunPendingChecks($in: $models.RunPendingChecksInput): $CancellablePromise<$models.MutationResult<$models.ExecutionJobAccepted>> {
    return $Call.ByID(138840161, $in);
}

export function SendExecutionMessage($in: $models.SendExecutionMessageInput): $CancellablePromise<$models.MutationResult<$models.ExecutionJobAccepted>> {
    return $Call.ByID(2090120471, $in);
}

export function SetHumanCheck($in: $models.SetHumanCheckInput): $CancellablePromise<$models.MutationResult<$models.CheckUpdate>> {
    return $Call.ByID(2726358031, $in);
}
