// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AgentCandidate {
    "candidateKey": string;
    "displayName": string;
    "command": string;
    "transport": string;
    "source": string;
    "resolvedExecutablePath"?: string;
    "args": string[] | null;
    "warnings": string[] | null;
}

export interface AgentCandidateQuery {
    "refresh": boolean;
}

export interface AgentCandidateResult {
    "items": AgentCandidate[] | null;
    "scannedAt": string;
    "warnings": string[] | null;
}

export interface AgentConnectionInput {
    "displayName": string;
    "command": string;
    "args": string[] | null;
    "transport": string;
    "environmentOverrides": EnvironmentVariableInput[] | null;
}

export interface AgentConnectionSummary {
    "connectionId": string;
    "displayName": string;
    "command": string;
    "transport": string;
    "resolvedExecutablePath": string;
    "args": string[] | null;
    "lastVerifiedAt": string;
    "protocolVersion": string;
    "authState": string;
    "schemaArtifactVersion": string;
}

export interface AgentJobAccepted {
    "jobId": string;
    "targetId": string;
    "methodType"?: string;
    "state": string;
    "acceptedAt": string;
}

export interface AgentProbeResult {
    "probeId": string;
    "configFingerprint": string;
    "compatibility": string;
    "protocolVersion"?: string;
    "authState": string;
    "expiresAt": string;
    "authMethods": AuthMethodView[] | null;
    "authObservation": AuthObservation;
    "capabilities"?: { [_ in string]?: boolean } | null;
}

export interface ArchiveProjectInput {
    "projectId": string;
    "expectedRevision": number;
    "operationId": string;
}

export interface ArchivedProject {
    "projectId": string;
    "revision": number;
    "archivedAt": string;
}

export interface AuthMethodView {
    "type": string;
    "authMethodId": string;
    "name": string;
    "description"?: string;
    "args": string[] | null;
    "environmentNames": string[] | null;
}

export interface AuthObservation {
    "status": string;
    "source": string;
    "observedAt": string;
    "processGeneration": number;
}

export interface AuthenticateAgentInput {
    "probeId": string;
    "connectionId": string;
    "authMethodId": string;
    "operationId": string;
}

export interface CheckAuthenticationInput {
    "connection": AgentConnectionInput;
    "operationId": string;
}

export interface CompleteSetupInput {
    "connection": AgentConnectionInput;
    "probeId": string;
    "operationId": string;
}

export interface CreateProjectInput {
    "name": string;
    "description": string;
    "workspacePath": string;
    "connectionId": string;
    "operationId": string;
}

export interface CreateRevisionInput {
    "sourceProjectId": string;
    "sourceProcedureId": string;
    "sourceProcedureRevision": number;
    "name": string;
    "workspacePath": string;
    "operationId": string;
}

export interface CreatedProject {
    "projectId": string;
    "revision": number;
    "status": string;
    "currentStage": string;
    "nextRoute": string;
    "createdAt": string;
}

export interface DeleteProjectInput {
    "projectId": string;
    "expectedRevision": number;
    "operationId": string;
}

export interface DeletedProject {
    "projectId": string;
    "deletedAt": string;
}

export interface DuplicateProjectInput {
    "sourceProjectId": string;
    "sourceRevision": number;
    "name": string;
    "workspacePath": string;
    "operationId": string;
}

export interface ElicitationResponseResult {
    "elicitationRequestId": string;
    "status": string;
    "respondedAt": string;
}

export interface EnvironmentVariableInput {
    "name": string;
    "value": string;
}

export interface ExportAccepted {
    "exportId": string;
    "jobId": string;
    "procedureId": string;
    "format": string;
    "destinationDisplayName": string;
    "acceptedAt": string;
}

export interface ExportProcedureInput {
    "procedureId": string;
    "procedureRevision": number;
    "format": string;
    "destination": VerifiedPathSelection;
    "overwriteConfirmed": boolean;
    "overwriteIdentity": OverwriteIdentity | null;
    "operationId": string;
}

export interface InitialSetupResult {
    "connection": AgentConnectionSummary;
    "nextRoute": string;
    "changeSequence": number;
}

export interface LogoutAccepted {
    "jobId": string;
    "connectionId": string;
    "state": string;
    "acceptedAt": string;
}

export interface LogoutAgentInput {
    "connectionId": string;
    "operationId": string;
}

export interface MutationReceipt {
    "operationId": string;
    "committedAt": string;
    "changeSequence": number;
}

export interface MutationResult<T> {
    "data": T;
    "receipt": MutationReceipt;
}

export interface OverwriteIdentity {
    "size": number;
    "sha256": string;
    "device": number;
    "inode": number;
}

export interface PrepareExportProcedureInput {
    "procedureId": string;
    "procedureRevision": number;
    "absolutePath": string;
}

export interface PreparedExportProcedure {
    "destination": VerifiedPathSelection;
    "overwriteIdentity": OverwriteIdentity | null;
    "destinationDisplayName": string;
    "overwriteRequired": boolean;
}

export interface ProjectListQuery {
    "search": string;
    "statuses": string[] | null;
    "sort": string;
    "cursor"?: string;
    "limit": number;
}

export interface ProjectListResult {
    "items": ProjectSummary[] | null;
    "total": number;
    "nextCursor": string | null;
    "generatedAt": string;
    "changeSequence": number;
}

export interface ProjectProgress {
    "completed": number;
    "total": number;
}

export interface ProjectSummary {
    "projectId": string;
    "name": string;
    "description": string;
    "workspacePath": string;
    "status": string;
    "currentStage": string;
    "progress": ProjectProgress;
    "attentionRank": number;
    "attentionReason": string | null;
    "updatedAt": string;
    "completedAt": string | null;
    "resumeRoute": string;
    "currentProcedureId": string | null;
    "currentProcedureRevision"?: number | null;
    "connectionState": string;
    "errorSummary": string | null;
    "revision": number;
}

export interface ReconnectSessionInput {
    "projectId": string;
    "expectedRevision": number;
    "strategy": string;
    "operationId": string;
}

export interface RespondToElicitationInput {
    "elicitationRequestId": string;
    "action": string;
    "content": string;
    "operationId": string;
}

export interface SessionConnectionAccepted {
    "projectId": string;
    "sessionId": string;
    "jobId": string;
    "state": string;
    "recoveryMode": string;
    "acceptedAt": string;
}

export interface StartupState {
    "initialSetupRequired": boolean;
    "defaultConnection"?: AgentConnectionSummary | null;
    "recoveryNotice"?: string;
    "nextRoute": string;
    "changeSequence": number;
}

export interface VerifiedPathSelection {
    "absolutePath": string;
    "resolvedPath": string;
    "verifiedRootId": string;
}
