// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AgentCandidate {
    "candidateKey": string;
    "displayName": string;
    "command": string;
    "transport": string;
    "source": string;
    "resolvedExecutablePath"?: string;
    "args": string[] | null;
    "warnings": string[] | null;
}

export interface AgentCandidateQuery {
    "refresh": boolean;
}

export interface AgentCandidateResult {
    "items": AgentCandidate[] | null;
    "scannedAt": string;
    "warnings": string[] | null;
}

export interface AgentConnectionInput {
    "displayName": string;
    "command": string;
    "args": string[] | null;
    "transport": string;
    "environmentOverrides": EnvironmentVariableInput[] | null;
}

export interface AgentConnectionSummary {
    "connectionId": string;
    "displayName": string;
    "command": string;
    "transport": string;
    "resolvedExecutablePath": string;
    "args": string[] | null;
    "lastVerifiedAt": string;
    "protocolVersion": string;
    "authState": string;
    "schemaArtifactVersion": string;
}

export interface AgentJobAccepted {
    "jobId": string;
    "targetId": string;
    "methodType"?: string;
    "state": string;
    "acceptedAt": string;
}

export interface AgentProbeResult {
    "probeId": string;
    "configFingerprint": string;
    "compatibility": string;
    "protocolVersion"?: string;
    "authState": string;
    "expiresAt": string;
    "authMethods": AuthMethodView[] | null;
    "authObservation": AuthObservation;
    "capabilities"?: { [_ in string]?: boolean } | null;
}

export interface AuthMethodView {
    "type": string;
    "authMethodId": string;
    "name": string;
    "description"?: string;
    "args": string[] | null;
    "environmentNames": string[] | null;
}

export interface AuthObservation {
    "status": string;
    "source": string;
    "observedAt": string;
    "processGeneration": number;
}

export interface AuthenticateAgentInput {
    "probeId": string;
    "connectionId": string;
    "authMethodId": string;
    "operationId": string;
}

export interface CheckAuthenticationInput {
    "connection": AgentConnectionInput;
    "operationId": string;
}

export interface CompleteSetupInput {
    "connection": AgentConnectionInput;
    "probeId": string;
    "operationId": string;
}

export interface ElicitationResponseResult {
    "elicitationRequestId": string;
    "status": string;
    "respondedAt": string;
}

export interface EnvironmentVariableInput {
    "name": string;
    "value": string;
}

export interface InitialSetupResult {
    "connection": AgentConnectionSummary;
    "nextRoute": string;
    "changeSequence": number;
}

export interface LogoutAccepted {
    "jobId": string;
    "connectionId": string;
    "state": string;
    "acceptedAt": string;
}

export interface LogoutAgentInput {
    "connectionId": string;
    "operationId": string;
}

export interface MutationReceipt {
    "operationId": string;
    "committedAt": string;
}

export interface MutationResult<T> {
    "data": T;
    "receipt": MutationReceipt;
}

export interface RespondToElicitationInput {
    "elicitationRequestId": string;
    "action": string;
    "content": string;
    "operationId": string;
}

export interface StartupState {
    "initialSetupRequired": boolean;
    "defaultConnection"?: AgentConnectionSummary | null;
    "recoveryNotice"?: string;
    "nextRoute": string;
    "changeSequence": number;
}
