// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChangeProjectWorkspace(input: $models.ChangeProjectWorkspaceInput): $CancellablePromise<$models.MutationResult<application$0.WorkspaceChangeAccepted>> {
    return $Call.ByID(489623341, input);
}

export function GetPreparation(input: $models.PreparationViewQuery): $CancellablePromise<application$0.PreparationView> {
    return $Call.ByID(18778174, input);
}

export function SaveCheckPlan(input: $models.SaveCheckPlanInput): $CancellablePromise<$models.MutationResult<application$0.SavedCheckPlan>> {
    return $Call.ByID(2230699497, input);
}

export function SavePreparationBrief(input: $models.SavePreparationBriefInput): $CancellablePromise<$models.MutationResult<application$0.PreparationUpdate>> {
    return $Call.ByID(3827854321, input);
}

export function SaveSessionPermissionPolicy(input: $models.SaveSessionPermissionPolicyInput): $CancellablePromise<$models.MutationResult<application$0.SessionPermissionPolicy>> {
    return $Call.ByID(3814117507, input);
}

export function SendPreparationMessage(input: $models.SendPreparationMessageInput): $CancellablePromise<$models.MutationResult<application$0.AcceptedTurn>> {
    return $Call.ByID(3930952125, input);
}

export function StartExecution(input: $models.StartExecutionInput): $CancellablePromise<$models.MutationResult<application$0.ExecutionStarted>> {
    return $Call.ByID(2744344285, input);
}
