// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CompleteProcedure($in: $models.CompleteProcedureInput): $CancellablePromise<$models.MutationResult<application$0.ProcedureCompleted>> {
    return $Call.ByID(1672821581, $in);
}

export function ExportProcedure($in: $models.ExportProcedureInput): $CancellablePromise<$models.MutationResult<$models.ExportAccepted>> {
    return $Call.ByID(906820986, $in);
}

export function GetEvidence($in: $models.GetEvidenceInput): $CancellablePromise<$models.ProcedureEvidenceDetail> {
    return $Call.ByID(3265100212, $in);
}

export function GetProcedure(query: $models.ProcedureViewQuery): $CancellablePromise<application$0.ProcedureView> {
    return $Call.ByID(2087193246, query);
}

export function PrepareExportProcedure($in: $models.PrepareExportProcedureInput): $CancellablePromise<$models.PreparedExportProcedure> {
    return $Call.ByID(40576585, $in);
}

export function RequestProcedureRevision($in: application$0.RequestProcedureRevisionInput): $CancellablePromise<$models.MutationResult<application$0.AcceptedTurn>> {
    return $Call.ByID(1204010540, $in);
}

export function SaveProcedureDraft($in: $models.SaveProcedureDraftInput): $CancellablePromise<$models.MutationResult<application$0.ProcedureSaved>> {
    return $Call.ByID(3058994050, $in);
}
