// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trace$0 from "../../trace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveProject(input: $models.ArchiveProjectInput): $CancellablePromise<$models.MutationResult<$models.ArchivedProject>> {
    return $Call.ByID(2033535480, input);
}

export function CreateProject(input: $models.CreateProjectInput): $CancellablePromise<$models.MutationResult<$models.CreatedProject>> {
    return $Call.ByID(909220800, input);
}

export function CreateRevision(input: $models.CreateRevisionInput): $CancellablePromise<$models.MutationResult<$models.CreatedProject>> {
    return $Call.ByID(3792176978, input);
}

export function DeleteProject(input: $models.DeleteProjectInput): $CancellablePromise<$models.MutationResult<$models.DeletedProject>> {
    return $Call.ByID(2850077653, input);
}

export function DuplicateProject(input: $models.DuplicateProjectInput): $CancellablePromise<$models.MutationResult<$models.CreatedProject>> {
    return $Call.ByID(1269568665, input);
}

export function ExportProcedure(input: $models.ExportProcedureInput): $CancellablePromise<$models.MutationResult<$models.ExportAccepted>> {
    return $Call.ByID(4197448530, input);
}

export function ListProjects(input: $models.ProjectListQuery): $CancellablePromise<$models.ProjectListResult> {
    return $Call.ByID(2753046913, input);
}

export function PrepareExportProcedure(input: $models.PrepareExportProcedureInput): $CancellablePromise<$models.PreparedExportProcedure> {
    return $Call.ByID(199265905, input);
}

export function ReconnectProjectSession(input: $models.ReconnectSessionInput): $CancellablePromise<$models.MutationResult<$models.SessionConnectionAccepted>> {
    return $Call.ByID(1544727671, input);
}

export function SetTrace(writer: trace$0.Writer | null): $CancellablePromise<void> {
    return $Call.ByID(3148781442, writer);
}
