// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckAuthentication(input: $models.CheckAuthenticationInput): $CancellablePromise<$models.AgentProbeResult> {
    return $Call.ByID(1491784629, input);
}

export function CompleteInitialSetup(input: $models.CompleteSetupInput): $CancellablePromise<$models.MutationResult<$models.InitialSetupResult>> {
    return $Call.ByID(2972149189, input);
}

export function GetStartupState(): $CancellablePromise<$models.StartupState> {
    return $Call.ByID(2958778619);
}

export function ListAgentCandidates(query: $models.AgentCandidateQuery): $CancellablePromise<$models.AgentCandidateResult> {
    return $Call.ByID(748173126, query);
}
