// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as events$0 from "../../../../yukihito-jokyu/TEJUN/internal/adapter/wails/events/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:event": events$0.AppEvent;
        }
    }
}
