// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execution$0 from "../domain/execution/models.js";

export interface AcceptedTurn {
    "sessionId": string;
    "turnId": string;
    "jobId": string;
    "acceptedAt": string;
}

export interface AgentConnectionSummary {
    "connectionId": string;
    "displayName": string;
    "command": string;
    "args": string[] | null;
    "transport": string;
    "resolvedExecutablePath": string;
    "lastVerifiedAt": string;
    "protocolVersion": string;
    "authState": string;
    "schemaArtifactVersion": string;
}

export interface AssignedCheckID {
    "clientKey": string;
    "checkId": string;
}

export interface CheckEvidence {
    "ai": EvidenceSummary[] | null;
    "human": EvidenceSummary[] | null;
}

export interface CheckItem {
    "checkId": string;
    "sequence": number;
    "title": string;
    "instruction": string;
    "expectedResult": string;
    "suggestedCommand": string;
    "aiRequired": boolean;
    "humanRequired": boolean;
    "humanEvidenceRequirement": string;
}

export interface CheckPlanView {
    "planId": string;
    "revision": number;
    "items": CheckItem[] | null;
}

export interface CheckSideView {
    "required": boolean;
    "status": string;
    "checked": boolean;
    "checkedAt": string | null;
    "failureSummary": string;
}

export interface ContentPart {
    "type": string;
    "text": string;
    "evidenceId": string;
    "url": string;
    "name": string;
    "mimeType": string;
}

export interface ConversationItem {
    "messageId": string;
    "turnId": string;
    "role": string;
    "status": string;
    "content": ContentPart[] | null;
    "createdAt": string;
    "sequence": number;
}

export interface ConversationPage {
    "items": ConversationItem[] | null;
    "previousCursor": number | null;
    "hasPrevious": boolean;
}

export interface ElicitationRequestView {
    "elicitationRequestId": string;
    "sessionId": string;
    "scope": { [_ in string]?: any } | null;
    "requestedSchema": { [_ in string]?: any } | null;
    "url": string;
    "mode": string;
    "message": string;
    "status": string;
    "requestedAt": string;
    "expiresAt": string | null;
}

export interface EvidenceSummary {
    "evidenceId": string;
    "actor": string;
    "kind": string;
    "displayName": string;
    "mimeType": string;
    "size": number;
    "previewUrl": string;
    "createdAt": string;
}

export interface ExecutionCheckView {
    "checkId": string;
    "sequence": number;
    "title": string;
    "instruction": string;
    "expectedResult": string;
    "ai": CheckSideView;
    "human": CheckSideView;
    "humanEvidenceRequirement": string;
    "overallStatus": string;
    "evidence": CheckEvidence;
}

export interface ExecutionReadiness {
    "canGenerateProcedure": boolean;
    "blockingReasons": ReadinessIssue[] | null;
}

export interface ExecutionStarted {
    "projectId": string;
    "executionId": string;
    "sessionId": string;
    "nextRoute": string;
    "executionRevision": number;
    "startedAt": string;
}

export interface ExecutionSummary {
    "executionId": string;
    "status": string;
    "revision": number;
    "startedAt": string;
    "completedAt": string | null;
}

export interface ExecutionView {
    "project": ProjectHeader;
    "execution": ExecutionSummary;
    "session": SessionSummary;
    "activeRun": RunSummary | null;
    "checks": ExecutionCheckView[] | null;
    "pendingPermissions": PermissionRequestView[] | null;
    "conversation": ConversationPage;
    "readiness": ExecutionReadiness;
    "changeSequence": number;
}

export interface PermissionRequestView {
    "permissionRequestId": string;
    "sessionId": string;
    "runId": string;
    "toolCall": ToolCallPresentation;
    "options": execution$0.PermissionOption[] | null;
    "status": string;
    "requestedAt": string;
    "expiresAt": string | null;
}

export interface PreparationBrief {
    "purpose": string;
    "completionCriteria": string[] | null;
    "intendedUsers": string;
    "revision": number;
}

export interface PreparationChat {
    "sessionId": string;
    "title": string;
    "startedAt": string;
}

export interface PreparationUpdate {
    "projectId": string;
    "preparationRevision": number;
    "brief": PreparationBrief;
    "affectedCheckIds": string[] | null;
    "readiness": Readiness;
    "updatedAt": string;
}

export interface PreparationView {
    "project": ProjectHeader;
    "preparation": PreparationBrief;
    "checkPlan": CheckPlanView;
    "session": SessionSummary | null;
    "conversation": ConversationPage;
    "chats": PreparationChat[] | null;
    "elicitations": ElicitationRequestView[] | null;
    "readiness": Readiness;
    "changeSequence": number;
}

export interface ProjectHeader {
    "projectId": string;
    "name": string;
    "description": string;
    "workspacePath": string;
    "status": string;
    "currentStage": string;
    "revision": number;
    "createdAt": string;
    "updatedAt": string;
    "connection": AgentConnectionSummary | null;
}

export interface Readiness {
    "canStartExecution": boolean;
    "blockingReasons": ReadinessIssue[] | null;
}

export interface ReadinessIssue {
    "code": string;
    "message": string;
    "checkId": string;
    "evidenceRequirement": string;
}

export interface RunSummary {
    "runId": string;
    "status": string;
    "targetedCheckIds": string[] | null;
    "startedAt": string | null;
    "finishedAt": string | null;
}

export interface SavedCheckPlan {
    "projectId": string;
    "preparationRevision": number;
    "planRevision": number;
    "items": CheckItem[] | null;
    "assignedIds": AssignedCheckID[] | null;
    "readiness": Readiness;
    "updatedAt": string;
}

export interface SessionConfigChoice {
    "value": string;
    "name": string;
    "description": string;
}

export interface SessionConfigGroup {
    "groupId": string;
    "name": string;
    "options": SessionConfigChoice[] | null;
}

export interface SessionConfigOption {
    "type": string;
    "configId": string;
    "name": string;
    "description": string;
    "category": string;
    "currentValue": any;
    "options"?: SessionConfigOptionChoices | null;
}

export interface SessionConfigOptionChoices {
    "layout": string;
    "items"?: SessionConfigChoice[] | null;
    "groups"?: SessionConfigGroup[] | null;
}

export interface SessionMode {
    "modeId": string;
    "name": string;
    "description": string;
}

export interface SessionModes {
    "currentModeId": string;
    "available": SessionMode[] | null;
}

export interface SessionPermissionPolicy {
    "sessionId": string;
    "mode": string;
    "revision": number;
}

export interface SessionSummary {
    "sessionId": string;
    "state": string;
    "protocolVersion": string;
    "agentName": string;
    "agentVersion": string;
    "startedAt": string;
    "disconnectedAt": string | null;
    "permissionPolicy": SessionPermissionPolicy;
    "revision": number;
    "changeSequence": number;
    "capabilities": { [_ in string]?: any } | null;
    "modes": SessionModes | null;
    "configOptions": SessionConfigOption[] | null;
}

export interface ToolCallDetail {
    "label": string;
    "value": string;
}

export interface ToolCallLocation {
    "path": string;
    "line": number | null;
}

export interface ToolCallPresentation {
    "toolCallId": string;
    "title": string;
    "kind": string;
    "status": string;
    "command": string;
    "locations": ToolCallLocation[] | null;
    "details": ToolCallDetail[] | null;
}

export interface WorkspaceChangeAccepted {
    "projectId": string;
    "projectRevision": number;
    "previousSessionId": string;
    "sessionId": string;
    "jobId": string;
    "state": string;
    "conversationContinuity": string;
    "acceptedAt": string;
}
