// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppEvent {
    "eventId": string;
    "name": string;
    "emittedAt": string;
    "aggregateType": string;
    "aggregateId": string;
    "changeSequence": number;
    "streamKey": string;
    "streamRevision": number;
    "correlation": Correlation;
    "payload": { [_ in string]?: any } | null;
}

export interface Correlation {
    "projectId"?: string;
    "sessionId"?: string;
    "turnId"?: string;
    "executionId"?: string;
    "runId"?: string;
    "procedureId"?: string;
    "jobId"?: string;
}
